### ISSUE TITLE
Вопрос

### ISSUE THREAD

**Issue by Daniikaa** [U61vashka/MC-Auth-with-Link#20]
При вводе команды произошла ошибка, сообщите администрации. Пишет вк вот так когда пишу /аккаунты и так далее что это такое?

**Comment by Daniikaa** [comment]
Что делать?

**Comment by x7lare** [comment]
предлагаю сделать пососаку

**Comment by U61vashka** [comment]
Нужно отправлять версию mc-auth, версию VK-API, версию BungeeCord/Velocity, саму ошибку, закрываю так как неправильно оформленный issue.

Как исправите открою
