### ISSUE TITLE
The problem of switching to the Hub

### ISSUE THREAD

**Issue by W1se-byte** [U61vashka/MC-Auth-with-Link#21]
After successful authentication - authorization on the Auth server, the plugin tries to redirect to the Hub (Hub to paper 1.16.5 and Auth to PaperSpigot 1.12.2), but it gives such a problem. And yes, I turned on ip-forwardding in bungeecord, because I tried it without a plugin and calmly goes in without this inscription.
![IMG_20221212_002634](https://user-images.githubusercontent.com/85458923/206929734-9185c0ea-36db-4afa-b2f5-a0032e9b17e6.jpg)

**Comment by U61vashka** [comment]
That is not problem of the plugin, i mentioned this on spigot discussion Page https://www.spigotmc.org/threads/mc-auth-with-telegram-vk-link.518966/page-3#post-4493465

Good luck, if you solved problem, i'll close issue
